### ISSUE TITLE
示例代码无法正常加载数据集

### ISSUE THREAD

**Issue by ningmenghongcha** [hkust-nlp/ceval#86]
```
from datasets import load_dataset
dataset=load_dataset(r"/home/lm-evaluation-harness-main/ceval-exam/",name="computer_network")

print(dataset['val'][0])
```

root@xxx:/home/lm-evaluation-harness-main# python load_datasets.py 
Resolving data files: 100%|███████████████████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 116539.57it/s]
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████| 52/52 [00:00<00:00, 87241.52it/s]
Traceback (most recent call last):
  File "/home/lm-evaluation-harness-main/load_datasets.py", line 7, in <module>
    dataset=load_dataset(r"/home/lm-evaluation-harness-main/ceval-exam/",name="computer_network")
  File "/usr/local/lib/python3.10/site-packages/datasets/load.py", line 2606, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/site-packages/datasets/load.py", line 2314, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/usr/local/lib/python3.10/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/usr/local/lib/python3.10/site-packages/datasets/builder.py", line 601, in _create_builder_config
    raise ValueError(
ValueError: BuilderConfig 'computer_network' not found. Available: ['default']

**Comment by HYZ17** [comment]
在我的笔记本电脑上可以正常工作，如下
<img width="567" alt="image" src="https://github.com/user-attachments/assets/0231f875-cdae-4c5b-9d3e-79f1d1e55892">

BTW，你不需要指定一个本地的目录，直接指定数据集的名字就行。
